### ISSUE TITLE
Extended keymap broken with new Windows 10 update

### ISSUE THREAD

**Issue by fklingler** [adunning/Mac-Keyboard-Layouts-for-Windows#2]
Hi! Thanks for these awesome keymaps.

I used the extended keymap with Windows 10 since Windows 10 has been released, and it seems to have been broken with a recent Windows 10 update, even when removing the keymap and reinstalling it.

It shows this in the language panel selection:
![image](https://cloud.githubusercontent.com/assets/282439/12745252/ac1000fe-c998-11e5-94ac-f7817c773107.png)

The normal keymap "United States-Macintosh" still works well.

**Comment by adunning** [comment]
Thanks for reporting this; I don't have access to a Windows 10 installation at the moment, so it will be some time before I can test it. It seems to be a common problem, e.g. <http://stackoverflow.com/questions/33239125/developing-a-custom-virtual-keyboard-for-windows-10>, but I haven't found any useful fixes yet.

**Comment by fklingler** [comment]
Ok, thanks for the feedback.
What are the differences between the Extended and the Normal keymap that makes the normal work but not the extended one?

Would you be able to create a keymap based on the normal one that just have the same behaviour that the Extended one for the C/Ç key? It seems to differ between the two, and for an unknown reason, I can't type Ç in some apps, even though I can in some others, like here on Chrome...

**Comment by adunning** [comment]
I suspect it has something to do with the extra layer under AltGr + Shift + ; (i.e. №). You can do anything you like with the layouts by editing with with Keyboard Layout Manager or 
the Microsoft Keyboard Layout Creator.

**Comment by fklingler** [comment]
Ok awesome, thanks

**Comment by gkovacs** [comment]
I made a pull request at https://github.com/adunning/Mac-Keyboard-Layouts-for-Windows/pull/3 (base repo: https://github.com/gkovacs/Mac-Keyboard-Layouts-for-Windows ) with executables built on Windows 10 64-bit, they seem to work correctly (whereas I get "unavailable input method" with the current ones)
