### ISSUE TITLE
Any chance of an International English layout?

### ISSUE THREAD

**Issue by trex78** [adunning/Mac-Keyboard-Layouts-for-Windows#4]
The US layout does nearly everything for me..   But there are two minor differences with the 'International English' keyboard... Any chance you could provide a layout for that?

Specifically.... 
 - The keys between Left-Shift and 'Z' should be swapped with the upper left key next to '1'.
 - The '£' key needs to be swapped with the '#' key...  (eg: Shift+3 should produce '£' while Alt-Gr+3 should produce '#')

**Comment by adunning** [comment]
Is 'International English' the PC keyboard? I must admit to being entirely unfamiliar with it. You can in any case make those changes by opening the original `.klc` files using Microsoft Keyboard Layout Creator.

**Comment by trex78** [comment]
No, it's just another variant of apple's extended keyboard available here
in the UK.
I was going to modify the layout myself, but even MKLC seems to be no
longer supported or updated by Microsoft and I didn't much relish the idea
of installing an ancient .NET framework on Win 10 just to try :)
I've adapted now, so all good. Thx.

**Comment by adunning** [comment]
Hadn't realized they had discontinued it; rather unfortunate. I'll close this issue for now, but let me know if you run into more problems.
