### ISSUE TITLE
AltGr-m not producing µ on Windows 10 1709

### ISSUE THREAD

**Issue by bhtooefr** [adunning/Mac-Keyboard-Layouts-for-Windows#5]
This may be Microsoft's bug, but I've noticed that µ can no longer be generated by issuing AltGr-m using this layout. Shift-AltGr-m still produces Â, though.

I also attempted freshly rebuilding the layout from source (on the affected Windows 10 64-bit device), with no change in symptoms.

Any suggestions?

**Comment by adunning** [comment]
That's really weird; this just started with the new build of Windows 10? I don't yet have a copy of Windows 10 (my computer at work is still stuck on Windows 7), but will test it when I can get access to it.

**Comment by bhtooefr** [comment]
I don't recall it happening before 1709, but I've noticed the issue for a while on this machine with 1709. I can try on some other machines tomorrow, actually, including one still on 1607.

**Comment by bhtooefr** [comment]
OK, I think it's an issue with my system specifically - another system of mine on 1709 doesn't demonstrate this issue. (Both are 64-bit.) I'll close this issue.

**Comment by adunning** [comment]
That's weird; many thanks for testing, as that saves me time!

**Comment by bhtooefr** [comment]
Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this.

GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.

Deleted that shortcut, all good now.

**Comment by Norepidopamine** [comment]
> 
> 
> Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this (so as to avoid the problem presented in [this xkcd](https://xkcd.com/979/)).
> 
> GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.
> 
> Deleted that shortcut, all good now.

Bullseye!

**Comment by ka-steve** [comment]
> Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this (so as to avoid the problem presented in [this xkcd](https://xkcd.com/979/)).
> 
> GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.
> 
> Deleted that shortcut, all good now.

Thanks. Ctrl+Alt+m is `<` on a Hungarian layout, so as a programmer it was pretty inconvenient when it stopped working. I suspected another program must have been hijacking it because earlier I had the same experience with the Mobaxterm SSH client, but yes, this time it was the GeForce Experience. 

It's not necessarily easy to find the relevant settings, but as of June of 2021 on Windows, v3.22, this was the process for me:
 - Cogwheel icon in the header;
 - "General" in the left menubar (you should already be here);
 - "In-Game Overlay" box / SETTINGS button;
 - And finally in the popup: Keyboard settings.

I had to google it to realize the Keyboard settings will be under the In-Game Overlay, so I figured this could be useful for others too.

**Comment by bhtooefr** [comment]
Also, another thing that conflicts, this time with AltGr+u: the drivers for [this Monoprice graphics tablet](https://www.monoprice.com/product?p_id=10594) (and probably anything else made by Huion) bind to Ctrl+Alt+u.

So, if you want to make umlauts, you need to exit the utility, even if the tablet is disconnected and the utility has a red X over its notification area icon. (I discovered this a while ago, but the most recent comment reminded me to document it.)

**Comment by MicAtWork** [comment]
Seems that also Magnifier blocks that shortcut: https://superuser.com/a/1284172 turn it off in settings > Accessibility > Magnifier

**Comment by LAinox001** [comment]
> Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this (so as to avoid the problem presented in [this xkcd](https://xkcd.com/979/)).
> 
> GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.
> 
> Deleted that shortcut, all good now.

Holy Molly, 5 years later still accurate, thanks man !

**Comment by Ashenfae** [comment]
> Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this (so as to avoid the problem presented in [this xkcd](https://xkcd.com/979/)).
> 
> GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.
> 
> Deleted that shortcut, all good now.

Thank you for your service

**Comment by adunning** [comment]
Many thanks indeed for posting the solution to this!

**Comment by xLuoskrad** [comment]
> Found the issue, finally, and it's definitely not with this layout. Thought I'd comment so anyone who's having the same issue can find this (so as to avoid the problem presented in [this xkcd](https://xkcd.com/979/)).
> 
> GeForce Experience had bound Ctrl+Alt+m to microphone mute. Because AltGr is implemented as Ctrl+Alt, GeForce Experience was absorbing the keypresses.
> 
> Deleted that shortcut, all good now.

Thx a lot!
