### ISSUE TITLE
Remapping left special keys

### ISSUE THREAD

**Issue by thenikso** [adunning/Mac-Keyboard-Layouts-for-Windows#7]
Hello! 

This is not quite an issue but I believe it could be a valuable request for all lucky enough to find this repo!

The (standard) layout works perfectly for me. The last fix I would like to have is to remap left special keys from:

```
Ctrl   Win   Alt
```

To (having the right AltGr become Alt):
```
Win   AltGr  Ctrl
```

Do anyone here knows if this can be done and how?

Thanks!

**Comment by thenikso** [comment]
Well here I am solving this myself, check my solution using SharpKeys here https://github.com/randyrants/sharpkeys/issues/112

**Comment by adunning** [comment]
Thank you, belatedly! I've added this to the Wiki at <https://github.com/adunning/Mac-Keyboard-Layouts-for-Windows/wiki/Remapping-modifier-keys-to-imitate-Mac-layout>.
